#!/usr/bin/env python
import subprocess
import click

@click.command()
def deploy():
    click.echo("Running deploy command")
    print("Deploy Lambda")
    subprocess.check_call('cdk deploy', shell=True)

@click.command()
def build():
    click.echo("Running build command")
    print("Build Lambda Function")
    subprocess.check_call('npm run bundle-lambda', shell=True)

if __name__ == '__main__':
    deploy()

