version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase
      - node --version
      - npm --version
      - npm install -g npm@7.20.3
      - npm --version
  build:
    commands:
      - echo Entered the build phase
      - npm run bundle-lambda
      - npm run prettier
      - npm run lint
  post_build:
    commands:
      - echo Entered the post_build phase
    finally:
      - echo Build completed on `date`
