version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase
      - echo $CODEBUILD_BUILD_IMAGE
      - echo $CODEBUILD_LOG_PATH
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_DIR
      - node --version
      - npm --version
      - which python
      - npm install -g npm@7.20.3
      - npm --version
      - npm install
      - npm install -g aws-cdk
      - aws --version
      - cdk --version
  build:
    commands:
      - echo Entered the build phase
      - npm run bundle-lambda
      - npm run prettier
      - npm run lint
      - echo Deploy user-service
      - cdk deploy --verbose
  post_build:
    commands:
      - echo Entered the post_build phase
    finally:
      - echo Build completed on `date`
